[package]
name = "blackglass-polkit-helper"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "blackglass-polkit-helper"
path = "src/main.rs"

[lib]
name = "blackglass_polkit_helper"
path = "src/lib.rs"

[dependencies]
nix.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
tempfile.workspace = true
