//! Operator-socket auth: validates that incoming connections present
//! a token matching the one on disk. Defense in depth: refuses to use
//! a token file with permissions looser than 0600.
//!
//! The token file is generated by `blackglass-core` on first start
//! (if absent) and stored at
//! `~/.local/share/blackglass/operator.token` with mode 0600.

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use thiserror::Error;

const REQUIRED_MODE: u32 = 0o600;

#[derive(Debug, Error)]
pub enum AuthError {
    #[error("operator token file not found at {0}")]
    TokenFileMissing(PathBuf),
    #[error("operator token file {0} has mode {1:o}, expected 0600 (or stricter)")]
    TokenFileBadMode(PathBuf, u32),
    #[error("auth failed: presented token does not match")]
    AuthFailed,
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

#[derive(Debug, Clone)]
pub struct OperatorAuth {
    token_path: PathBuf,
    expected: Vec<u8>,
}

impl OperatorAuth {
    /// Read the token from disk. Validates the file's permissions.
    pub fn new(token_path: &Path) -> Self {
        Self {
            token_path: token_path.to_path_buf(),
            // Expected is populated lazily by `verify` so we don't hold a
            // stale copy if the file is rotated.
            expected: Vec::new(),
        }
    }

    /// Generate a fresh token at the given path (if absent) and return
    /// the auth handle. Mode 0600.
    pub fn generate_if_absent(token_path: &Path) -> Result<Self, AuthError> {
        if !token_path.exists() {
            if let Some(parent) = token_path.parent() {
                fs::create_dir_all(parent)?;
            }
            // 32 bytes of randomness, hex-encoded = 64 chars.
            let token = generate_token();
            fs::write(token_path, format!("{}\n", token))?;
            fs::set_permissions(token_path, fs::Permissions::from_mode(REQUIRED_MODE))?;
        }
        Ok(Self::new(token_path))
    }

    pub fn verify(&self, presented: &[u8]) -> Result<(), AuthError> {
        if !self.token_path.exists() {
            return Err(AuthError::TokenFileMissing(self.token_path.clone()));
        }
        let meta = fs::metadata(&self.token_path)?;
        let mode = meta.permissions().mode() & 0o777;
        if mode & 0o077 != 0 {
            return Err(AuthError::TokenFileBadMode(self.token_path.clone(), mode));
        }
        let expected = fs::read_to_string(&self.token_path)?;
        // Trim trailing newline (if any) on the expected token.
        let expected_trim = expected.trim_end_matches('\n');
        // Compare constant-time-ish: we just compare byte slices; this is
        // not a hot path so a simple `!=` is fine.
        if presented.trim_as_bytes() == expected_trim.as_bytes() {
            Ok(())
        } else {
            Err(AuthError::AuthFailed)
        }
    }
}

fn generate_token() -> String {
    use rand::Rng;
    let mut rng = rand::thread_rng();
    let bytes: [u8; 32] = rng.gen();
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

// Helper extension trait for trimming a `&[u8]` of trailing whitespace.
trait TrimAsBytes {
    fn trim_as_bytes(&self) -> &[u8];
}
impl TrimAsBytes for &[u8] {
    fn trim_as_bytes(&self) -> &[u8] {
        let mut end = self.len();
        while end > 0 && (self[end - 1] == b'\n' || self[end - 1] == b'\r' || self[end - 1] == b' ' || self[end - 1] == b'\t') {
            end -= 1;
        }
        &self[..end]
    }
}
